### ISSUE TITLE
Fix Travis CI test

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/Rock-Paper-Scissors-Web#11]
See https://travis-ci.org/TiagoDanin/Rock-Paper-Scissors-Web/builds/594217652?utm_source=github_status&utm_medium=notification. Problem with dependency

**Comment by fernandomaia** [comment]
Hey @TiagoDanin, can I take this one, please?

**Comment by TiagoDanin** [comment]
> Hey @TiagoDanin, can I take this one, please?

Yes :smile:
